
[main]
	#a
	a = false

[country]
	#是否对和平国家的领土保护
	country_protection = true

[chuck]
	#领土最大区块数
	max_chuck = 0.0
	del_entity = ["minecraft:creeper"]
	cant_open = []

[level]
	#农业时代需要的物品
	the_age_of_agriculture = []
	#蒸汽时代需要的物品
	the_age_of_steam = []
	#电气时代需要的物品
	the_electric_age = []
	#信息时代需要的物品
	information_age = []
	#核能时代需要的物品
	the_era_of_nuclear_energy = []

[chat]
	#是否接管消息事件
	Take_over_Message_Event = true
	#消息格式 例如%country_disname% %player_name% >> %message% 
	chat_format = "[%country_disname%] %player% >> %message% "

[war]
	#敌方最小开战等级
	war_start_min_level = 0.0
	#敌方最小开战人数
	war_start_player_number = 0.0

